Fix Additive Production
GTNewHorizons/Binnie pull request #33
Opened 2023-07-14 20:15 UTC by hacatu

See https://github.com/GTNewHorizons/ForestryMC/pull/55

2023-07-17 09:09 UTC, kuba6000 requested changes
Please adjust all frames, not only negative ones.
1.5x -> +0.5
2x -> +1

2023-07-18 15:16 UTC, kuba6000 requested changes

2023-07-18 15:28 UTC, hacatu commented on src/main/java/binnie/extrabees/apiary/machine/stimulator/CircuitType.java
> +        CircuitType.Inhibitor.logic.setModifier(EnumBeeModifier.PRODUCTION, -0.1f, 0.0f);// was 0.9x, now -0.1. limit
Can we not do this?  Apiaries can only have 3 frames, so nerfing frames has an impact.  However, alvearies can have up to 17 stimulators, so nerfing the bonus from a single circuit board would just make you require more to hit the cap.  I don't think that requiring 1.75x as many electron tubes per alveary adds anything

2023-07-18 15:46 UTC, kuba6000 commented on src/main/java/binnie/extrabees/apiary/machine/stimulator/CircuitType.java
> +        CircuitType.Inhibitor.logic.setModifier(EnumBeeModifier.PRODUCTION, -0.1f, 0.0f);// was 0.9x, now -0.1. limit
The prs are about transition, not balance. We are adjusting everything

2023-07-18 17:21 UTC, kuba6000 approved these changes

2023-07-18 18:30 UTC, Runakai1 approved these changes

2023-07-18 18:36 UTC, Dream-Master approved these changes

2023-07-18 18:36 UTC, merged